Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -94,6 +94,21 @@ jobs:
       - run:
           name: Run integration test
           command: ./gradlew cAT
+      - run:
+          name : check integration test result 
+          command : |
+            echo "testresult=$testresult"
+            if [ "$testresult" == "0" ] 
+            then
+                echo "test succeed!"
+            else
+                echo "There are test failures"
+                exit 1
+            fi
+      - store_artifacts:
+          path: "~/test_results"
+      - store_artifacts:
+          path: logcat.log
 workflows:
   version: 2
   build_test:
